### ISSUE TITLE
TODO for MVP 

### ISSUE THREAD

**Issue by applegrain** [applegrain/schedulary#1]
What: 
- online scheduling app 
- A Node app with a React client - and hopefully a database served by CouchDB. Hopefully.  

Why: 
- Students can log in and schedule appointments with Marissa so she has more time to focus on helping students find jobs and spends less time organizing her schedule. 

TODO: 
- [x] Marissa visits `tjat-attack.herokuapp.com`. She can select a month from a dropdown. There is a button "create new schedule". 
- [x]  Marissa selects a month and clicks "create new schedule" 
  - [x] this generates a new schedule for the month which will display on the DOM
  - [x] then she can select the days and times she wants to make available for appointments 
  - [x] then she clicks the button "create"... 
  - [ ] it generates two URL's, one for the subscriber (students: can view and schedule appointments) and one for the publisher (Marissa: can view and delete slots labeled as free)
- [ ] Students select time slots 
  - [ ] on selection, they add a purpose of the meeting and can add additional notes
- [ ] On the scheduling page, if someone selects a time, it becomes disabled for everyone viewing the page
- [ ] Students can deselect the slot they have picked
- [ ] After a student has made an appointment, he/she sees a link that downloads an iCal file and adds it to their calendar
- [ ] Marissa can delete time slots that have not yet been taken 

- [ ] test
- [ ] default the date to today's date
- [ ] disable selection of dates previous to the current date
- [ ] highlight dates with added slots
- [ ] have checks on the time input fields --> time specific
- [ ] can't add slots with conflicting times
- [ ] each slot should have a button to remove slots as well
- [ ] when slots are added, that day should be hihglighted in the calendar
   - [ ] when you click on that day, a box shows all of the appointments for that day

Extensions: 
- Implement Slack login with Passport.js 
- Add CouchDB

**Comment by applegrain** [comment]
rewrite!!
